version: '3.8'

services:
  admin-dashboard:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/getheyway
      - PORT=3001
      - VITE_API_BASE_URL=http://localhost:3001/api
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - admin-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    restart: unless-stopped
    networks:
      - admin-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - admin-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - admin-dashboard
    restart: unless-stopped
    networks:
      - admin-network

volumes:
  mongo_data:
  redis_data:

networks:
  admin-network:
    driver: bridge
